// Copyright (c) Petabridge, LLC. All rights reserved.
// Licensed under the Apache 2.0 license. See LICENSE file in the project root for full license information.

using System.Text;
using Termina.Diagnostics;

namespace Termina.Input;

/// <summary>
/// Parses escape sequences from individual <see cref="ConsoleKeyInfo"/> values arriving from
/// the active <see cref="Platform.IPlatformConsole"/>.
/// </summary>
/// <remarks>
/// <para>
/// Whether the bytes come from <c>Console.ReadKey</c> (Windows / fallback) or from raw stdin
/// reads via <see cref="Platform.UnixConsole"/>, each byte of an escape sequence arrives as a
/// separate <see cref="ConsoleKeyInfo"/>. This parser buffers them and detects:
/// </para>
/// <list type="bullet">
///   <item><description>Bracketed paste: <c>ESC[200~</c>…content…<c>ESC[201~</c> → <see cref="PasteEvent"/></description></item>
///   <item><description>SGR mouse events: <c>ESC[&lt;button;x;y(M|m)</c> → <see cref="MouseEvent"/> (press/release/drag/move, with modifiers and extended buttons decoded). Wheel events also emit a legacy <see cref="MouseScrollEvent"/>.</description></item>
///   <item><description>Focus tracking: <c>ESC[I</c> / <c>ESC[O</c> → <see cref="TerminalFocusEvent"/> (consumed so it never leaks as input).</description></item>
///   <item><description>CSI u (kitty keyboard protocol): <c>ESC[keycode;modifiersu</c> → <see cref="KeyPressed"/> with correct modifiers.</description></item>
///   <item><description>Legacy CSI tilde keys: <c>ESC[5~</c> / <c>ESC[5;5~</c> → <see cref="KeyPressed"/> (PgUp/PgDn/etc. with modifiers).</description></item>
///   <item><description>CSI arrow under xterm alternate-scroll mode: <c>ESC[A</c> / <c>ESC[B</c> → <see cref="MouseScrollEvent"/>.</description></item>
///   <item><description>SS3 arrow / function key: <c>ESC O A/B/C/D/H/F/P-S</c> → <see cref="KeyPressed"/> (arrows, Home/End, F1-F4).</description></item>
///   <item><description>Alt+Enter: <c>ESC</c> followed by <c>\r</c>/<c>\n</c> → <see cref="KeyPressed"/> with Alt modifier set.</description></item>
///   <item><description>Standalone <c>ESC</c>: emitted as <see cref="KeyPressed"/> after a 50 ms timeout with no follow-up character.</description></item>
/// </list>
/// <para>
/// CSI u sequences are generated by terminals that support the kitty keyboard protocol
/// (see <see href="https://sw.kovidgoyal.net/kitty/keyboard-protocol/"/>).
/// Standard terminals cannot distinguish Ctrl+Enter from Enter because both produce
/// the same byte (0x0D); the kitty protocol solves this by sending structured escape
/// sequences instead of raw bytes
/// (see <see href="https://blog.fsck.com/releases/2026/02/26/terminal-keyboard-protocol/"/>).
/// </para>
/// <para>
/// Call <see cref="Process"/> for each key received. When <see cref="IsBufferingEscape"/> is
/// <c>true</c>, the caller should use a short read timeout (≈50 ms) and call
/// <see cref="CheckEscapeTimeout"/> when no key arrives in time.
/// </para>
/// </remarks>
internal sealed class EscapeSequenceParser
{
    private enum State { Normal, AfterEscape, InBracketSequence, InSs3Sequence, PasteBuffering }

    private State _state = State.Normal;
    private readonly StringBuilder _seqBuffer = new();
    private readonly StringBuilder _pasteBuffer = new();
    private long _escapeReceivedAt;
    private int _pendingEndSeqPos;

    private const string PasteEndSeq = "\x1b[201~";

    // Injected clock for testing; defaults to Environment.TickCount64
    private readonly Func<long> _getTick;

    /// <summary>
    /// When <c>true</c>, the parser interprets bare <c>CSI A/B/C/D/H/F/P-S</c> (no params) as
    /// keyboard arrow / function keys instead of <see cref="MouseScrollEvent"/>. Set this when
    /// the kitty keyboard progressive enhancement <c>report_all_keys</c> (flag 8) is active —
    /// in that mode plain arrows are reported as canonical kitty escape codes and the only
    /// remaining source of bare <c>CSI A/B</c> is the <c>?1007h</c> alternate-scroll wheel.
    /// </summary>
    /// <remarks>
    /// When the kitty keyboard protocol is active <em>and</em> <c>?1007h</c> is also enabled,
    /// the only way to distinguish wheel-up from Up-arrow is for the parser to know which mode
    /// the terminal is in. The terminal's keyboard events get the kitty CSI-u / second-form
    /// shape; wheel events keep emitting the legacy <c>ESC OA/B</c> (DECCKM on) or
    /// <c>ESC [A/B</c> (DECCKM off) shape. With this flag set the parser routes the
    /// bare-CSI-arrow shape to <see cref="KeyPressed"/> (treating any matching SS3 as the wheel
    /// path instead — handled in <see cref="State.InSs3Sequence"/>).
    /// </remarks>
    public bool KittyReportAllKeysVisible { get; set; }

    /// <summary>
    /// Creates a parser using the system clock.
    /// </summary>
    public EscapeSequenceParser() : this(null) { }

    /// <summary>
    /// Creates a parser with an injectable clock function.
    /// Pass a custom <paramref name="getTick"/> for deterministic unit tests.
    /// </summary>
    /// <param name="getTick">Returns the current tick in milliseconds. If null, uses <see cref="Environment.TickCount64"/>.</param>
    internal EscapeSequenceParser(Func<long>? getTick)
    {
        _getTick = getTick ?? (() => Environment.TickCount64);
    }

    /// <summary>
    /// Whether the parser is currently buffering an incomplete escape sequence.
    /// When <c>true</c>, the caller should use a short read timeout so that a standalone
    /// <c>ESC</c> key (with no follow-up) can be flushed via <see cref="CheckEscapeTimeout"/>.
    /// </summary>
    public bool IsBufferingEscape =>
        _state == State.AfterEscape || _state == State.InBracketSequence || _state == State.InSs3Sequence;

    /// <summary>
    /// If 50 ms have elapsed since an <c>ESC</c> was buffered with no follow-up character,
    /// resets state and returns a <see cref="KeyPressed"/> for the standalone <c>ESC</c>.
    /// Returns <c>null</c> if no timeout has occurred.
    /// </summary>
    public KeyPressed? CheckEscapeTimeout()
    {
        if (_state == State.AfterEscape && _getTick() - _escapeReceivedAt > 50)
        {
            _state = State.Normal;
            return new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false));
        }
        return null;
    }

    /// <summary>
    /// Processes one key from <see cref="Console.ReadKey(bool)"/> and returns the application
    /// events that should be emitted as a result. The list may be empty (e.g., while buffering
    /// a multi-character escape sequence or silently consuming a mouse click event).
    /// </summary>
    /// <param name="key">The key to process.</param>
    /// <returns>Zero or more <see cref="IInputEvent"/> instances to emit.</returns>
    public IReadOnlyList<IInputEvent> Process(ConsoleKeyInfo key)
    {
        var results = new List<IInputEvent>(2);
        ProcessCore(key, results);
        return results;
    }

    private void ProcessCore(ConsoleKeyInfo key, List<IInputEvent> results)
    {
        TerminaTrace.Input.Trace(this, "ESP: state={0} KeyChar=0x{1:X4} Key={2}",
            _state, (int)key.KeyChar, key.Key);

        switch (_state)
        {
            case State.Normal:
                if (key.Key == ConsoleKey.Escape)
                {
                    _escapeReceivedAt = _getTick();
                    _state = State.AfterEscape;
                    TerminaTrace.Input.Debug(this, "ESP: ESC received → AfterEscape");
                }
                else
                {
                    results.Add(new KeyPressed(key));
                }
                break;

            case State.AfterEscape:
                if (key.KeyChar == '[')
                {
                    _seqBuffer.Clear();
                    _seqBuffer.Append('[');
                    _state = State.InBracketSequence;
                }
                else if (key.KeyChar == 'O')
                {
                    // SS3 introducer: ESC O <final> — used for arrow keys (and PF1-4) when
                    // the terminal is in cursor-key application mode (DECCKM, ?1h). With raw
                    // stdin input these reach us as ESC + 'O' + final byte.
                    _state = State.InSs3Sequence;
                }
                else if (key.Key == ConsoleKey.Enter || key.KeyChar == '\r' || key.KeyChar == '\n')
                {
                    // ESC + Enter = Alt+Enter (terminals send Alt as ESC prefix)
                    _state = State.Normal;
                    results.Add(new KeyPressed(
                        new ConsoleKeyInfo('\r', ConsoleKey.Enter, false, alt: true, false)));
                }
                else
                {
                    // Not a CSI sequence — flush ESC, then re-process this key as Normal
                    results.Add(new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false)));
                    _state = State.Normal;
                    ProcessCore(key, results);
                }
                break;

            case State.InBracketSequence:
                _seqBuffer.Append(key.KeyChar);
                var seq = _seqBuffer.ToString();

                // Bracketed paste start: ESC[200~
                if (seq == "[200~")
                {
                    _pasteBuffer.Clear();
                    _pendingEndSeqPos = 0;
                    _state = State.PasteBuffering;
                    TerminaTrace.Input.Debug(this, "ESP: Paste start detected → PasteBuffering");
                    break;
                }

                // Legacy xterm/VT function-key form: ESC[<num>~ or ESC[<num>;<mods>~.
                // Keep this after bracketed paste so ESC[200~ remains the paste sentinel.
                if (key.KeyChar == '~'
                    && LegacyCsiKeyboardDecoder.TryDecode(seq, out var legacyKeyEvent)
                    && legacyKeyEvent is not null)
                {
                    TerminaTrace.Input.Debug(this, "ESP: legacy CSI tilde {0} → {1}", seq, legacyKeyEvent);
                    results.Add(legacyKeyEvent);
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // Focus tracking (CSI ?1004h): ESC[I = focus gained, ESC[O = focus lost.
                if (seq == "[I" || seq == "[O")
                {
                    TerminaTrace.Input.Debug(this, "ESP: focus {0}", seq == "[I" ? "in" : "out");
                    results.Add(new TerminalFocusEvent(seq == "[I"));
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // CSI u (kitty keyboard protocol): ESC[keycode;modifiersu
                if (key.KeyChar == 'u' && seq.Length >= 2)
                {
                    if (TryParseCsiU(seq, out var csiEvent) && csiEvent is not null)
                    {
                        TerminaTrace.Input.Debug(this, "ESP: CSI u detected: {0}", seq);
                        results.Add(csiEvent);
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // SGR mouse event: ESC[<button;x;yM (press) or ESC[<button;x;ym (release).
                // EmitMouseSgrEvent fully decodes clicks/drags/modifiers/extended buttons into a
                // rich MouseEvent (and a legacy MouseScrollEvent for wheel ticks).
                if (seq.Length >= 2 && seq[1] == '<' && (key.KeyChar == 'M' || key.KeyChar == 'm'))
                {
                    EmitMouseSgrEvent(seq, results);

                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // Wheel-as-CSI-arrow under xterm alternate-scroll mode (?1007h).
                // Routing of bare CSI A/B depends on whether the kitty keyboard protocol is
                // active:
                //   - Kitty inactive: bare CSI A/B is the legacy ?1007h wheel emission
                //     (because real arrows arrive as SS3 OA/B under DECCKM).
                //   - Kitty active: bare CSI A/B/C/D/H/F/P-S are the kitty canonical no-mod
                //     keyboard form; wheel still emits the DECCKM-controlled SS3 form, so the
                //     CSI form is unambiguously a real key.
                if (seq.Length == 2 && IsArrowOrFunctionalFinal(key.KeyChar))
                {
                    if (KittyReportAllKeysVisible)
                    {
                        var ck = FunctionalFinalToKey(key.KeyChar);
                        if (ck != ConsoleKey.None)
                        {
                            TerminaTrace.Input.Debug(this, "ESP: CSI {0} (kitty no-mod) → KeyPressed({1})", key.KeyChar, ck);
                            results.Add(new KeyPressed(new ConsoleKeyInfo('\0', ck, false, false, false)));
                        }
                    }
                    else if (key.KeyChar == 'A' || key.KeyChar == 'B')
                    {
                        var delta = key.KeyChar == 'A' ? +1 : -1;
                        TerminaTrace.Input.Debug(this, "ESP: CSI {0} → MouseScrollEvent({1})", key.KeyChar, delta);
                        results.Add(new MouseScrollEvent(delta));
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // Kitty "second form" with parameters: CSI 1;<mods>[:<event>] [ABCDEFHPQRS]
                // Real arrows / function keys with a modifier pressed when kitty's
                // disambiguate (bit 1) or report_all_keys (bit 8) flag is set.
                if (IsArrowOrFunctionalFinal(key.KeyChar) && seq.Length >= 3 && seq[1] != '<')
                {
                    if (TryParseKittySecondForm(seq, out var keyEvent) && keyEvent is not null)
                    {
                        TerminaTrace.Input.Debug(this, "ESP: kitty second-form {0} → {1}", seq, keyEvent);
                        results.Add(keyEvent);
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                    break;
                }

                // If this sequence can no longer match any recognized pattern, flush as raw keys
                if (!CouldLeadToRecognizedSequence(seq))
                {
                    results.Add(new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false)));
                    foreach (var c in seq)
                    {
                        results.Add(new KeyPressed(new ConsoleKeyInfo(c, ConsoleKey.None, false, false, false)));
                    }
                    _seqBuffer.Clear();
                    _state = State.Normal;
                }
                break;

            case State.InSs3Sequence:
            {
                // ESC O A/B/C/D -> arrow keys delivered by the terminal under DECCKM (?1h).
                // We re-emit these as the same ConsoleKeyInfo shape Console.ReadKey used to
                // produce for arrow keys, so existing focus/scroll handlers see no difference.
                //
                // EXCEPTION: when the kitty keyboard protocol is active, real keyboard arrows
                // arrive via the kitty CSI-u / second-form path instead, so any remaining
                // SS3 OA/OB at this point must be the ?1007h wheel emission under DECCKM on.
                // (SS3 OC/OD never come from the wheel — there is no horizontal wheel.)
                if (Ss3KeyboardDecoder.TryDecode(key.KeyChar, KittyReportAllKeysVisible, out var ss3Event))
                {
                    TerminaTrace.Input.Debug(this, "ESP: SS3 O{0} → {1}", key.KeyChar, ss3Event);
                    if (ss3Event is not null)
                        results.Add(ss3Event);
                }
                else
                {
                    // Unknown SS3 sequence — flush ESC + 'O' + this char as raw keys.
                    results.Add(new KeyPressed(new ConsoleKeyInfo('\x1b', ConsoleKey.Escape, false, false, false)));
                    results.Add(new KeyPressed(new ConsoleKeyInfo('O', ConsoleKey.O, false, false, false)));
                    results.Add(new KeyPressed(new ConsoleKeyInfo(key.KeyChar, ConsoleKey.None, false, false, false)));
                }
                _state = State.Normal;
                break;
            }

            case State.PasteBuffering:
                // Detect ESC[201~ end sentinel one character at a time
                var expectedChar = _pendingEndSeqPos == 0 ? '\x1b' : PasteEndSeq[_pendingEndSeqPos];
                var isEscChar = key.Key == ConsoleKey.Escape || key.KeyChar == '\x1b';
                var charMatches = _pendingEndSeqPos == 0 ? isEscChar : key.KeyChar == expectedChar;

                if (charMatches)
                {
                    _pendingEndSeqPos++;
                    if (_pendingEndSeqPos == PasteEndSeq.Length)
                    {
                        TerminaTrace.Input.Debug(this, "ESP: Paste end detected, {0} chars", _pasteBuffer.Length);
                        results.Add(new PasteEvent(_pasteBuffer.ToString()));
                        _pasteBuffer.Clear();
                        _pendingEndSeqPos = 0;
                        _state = State.Normal;
                    }
                }
                else if (_pendingEndSeqPos > 0)
                {
                    // Partial end-sequence match failed — the buffered chars belong to paste content
                    _pasteBuffer.Append(PasteEndSeq[.._pendingEndSeqPos]);
                    _pendingEndSeqPos = 0;
                    _pasteBuffer.Append(key.KeyChar);
                }
                else
                {
                    _pasteBuffer.Append(key.KeyChar);
                }
                break;
        }
    }

    /// <summary>
    /// Returns <c>true</c> if the accumulated bracket sequence could still lead to a recognized
    /// escape sequence. Used to decide whether to keep buffering or flush the sequence as raw keys.
    /// </summary>
    private static bool CouldLeadToRecognizedSequence(string seq)
    {
        // Could still be paste start "[200~"
        const string pasteStart = "[200~";
        if (seq.Length <= pasteStart.Length && pasteStart.StartsWith(seq, StringComparison.Ordinal))
            return true;

        // Complete but still-unrecognized CSI tilde-terminated sequences flush as raw
        // KeyPressed events rather than keeping the parser stuck in InBracketSequence.
        if (seq.Length >= 3 && seq[^1] == '~')
            return false;

        // Could be a CSI u sequence "[keycode;modifiersu" — digits, semicolons, colons, up to ~32 chars
        if (seq.Length >= 2 && seq.Length <= 32 && (char.IsDigit(seq[1]) || seq[1] == ';' || seq[1] == ':'))
            return true;

        // Could be an SGR mouse event "[<button;x;yM" — open-ended length up to ~30 chars
        if (seq.Length >= 2 && seq[1] == '<' && seq.Length <= 30)
            return true;

        // Could be wheel-as-CSI-arrow under ?1007h: "[A" or "[B" / kitty second-form "[1;NA"
        if (seq == "[")
            return true;

        return false;
    }

    /// <summary>True for CSI finals that represent an arrow / Home/End / F1-F4 / KP_Begin.</summary>
    /// <remarks>
    /// <c>'E'</c> is KP_Begin (numpad-5 / "center" with NumLock off). It is recognized here so
    /// the shape <c>ESC[E</c> / <c>ESC[1;&lt;mods&gt;E</c> is consumed rather than flushed as raw
    /// keys, but <see cref="FunctionalFinalToKey"/> has no mapping for it (no equivalent
    /// <see cref="ConsoleKey"/>), so it is intentionally swallowed.
    /// </remarks>
    private static bool IsArrowOrFunctionalFinal(char c) =>
        c is 'A' or 'B' or 'C' or 'D' or 'E' or 'F' or 'H' or 'P' or 'Q' or 'R' or 'S';

    /// <summary>Maps the CSI second-form final char to a <see cref="ConsoleKey"/>.</summary>
    /// <remarks>
    /// <c>'E'</c> (KP_Begin) returns <see cref="ConsoleKey.None"/> on purpose — call sites
    /// treat that as "recognized but no event to emit" so the sequence is consumed silently.
    /// </remarks>
    private static ConsoleKey FunctionalFinalToKey(char c) => c switch
    {
        'A' => ConsoleKey.UpArrow,
        'B' => ConsoleKey.DownArrow,
        'C' => ConsoleKey.RightArrow,
        'D' => ConsoleKey.LeftArrow,
        'H' => ConsoleKey.Home,
        'F' => ConsoleKey.End,
        'P' => ConsoleKey.F1,
        'Q' => ConsoleKey.F2,
        'R' => ConsoleKey.F3,
        'S' => ConsoleKey.F4,
        _ => ConsoleKey.None,
    };

    /// <summary>
    /// Attempts to parse a kitty keyboard "second form" sequence: <c>[1;modifiers[:event] final</c>
    /// where <c>final</c> is one of <c>A B C D E F H P Q R S</c>.
    /// </summary>
    /// <param name="seq">The buffered sequence string, e.g. <c>[1;5A</c> or <c>[1;2:1A</c>.</param>
    /// <param name="result">
    /// On <c>true</c> return: the resulting <see cref="KeyPressed"/> when this was a press event,
    /// or <c>null</c> when a repeat/release event was parsed and intentionally swallowed.
    /// </param>
    /// <returns>
    /// <c>true</c> if the sequence was recognized (whether or not an event is produced).
    /// </returns>
    private static bool TryParseKittySecondForm(string seq, out KeyPressed? result)
    {
        result = null;
        if (seq.Length < 3 || seq[0] != '[') return false;
        var final = seq[^1];
        var key = FunctionalFinalToKey(final);
        if (key == ConsoleKey.None) return false;

        // Strip leading '[' and trailing final → "1;modifiers[:event]"
        var inner = seq[1..^1];
        var semicolon = inner.IndexOf(';');
        if (semicolon < 0) return false;

        // First field must be "1" for the second form.
        if (inner[..semicolon] != "1") return false;
        var rest = inner[(semicolon + 1)..];

        // Parse modifiers and optional event-type subfield.
        var colon = rest.IndexOf(':');
        var modPart = colon < 0 ? rest : rest[..colon];
        if (!int.TryParse(modPart, out var modValue) || modValue < 1) return false;

        // Event type: 1 = press (default), 2 = repeat, 3 = release. Only emit press events.
        if (colon >= 0)
        {
            if (!int.TryParse(rest[(colon + 1)..], out var eventType)) return false;
            if (eventType != 1) return true; // parsed-and-swallowed; result stays null
        }

        var modBits = modValue - 1;
        var shift = (modBits & 1) != 0;
        var alt = (modBits & 2) != 0;
        var ctrl = (modBits & 4) != 0;
        result = new KeyPressed(new ConsoleKeyInfo('\0', key, shift, alt, ctrl));
        return true;
    }

    /// <summary>
    /// Attempts to parse a CSI u (kitty keyboard protocol) sequence.
    /// Format: <c>[keycode;modifiersu</c> where keycode is a Unicode codepoint
    /// and modifiers is a 1-based bitmask (shift=2, alt=3, ctrl=5, etc.).
    /// See <see href="https://sw.kovidgoyal.net/kitty/keyboard-protocol/"/> for the full specification.
    /// </summary>
    /// <param name="seq">The buffered sequence string, e.g. <c>[13;5u</c>.</param>
    /// <param name="result">The resulting <see cref="KeyPressed"/> event, if parsing succeeded.</param>
    /// <returns><c>true</c> if the sequence was successfully parsed.</returns>
    private static bool TryParseCsiU(string seq, out KeyPressed? result)
    {
        result = null;

        // seq = "[keycode[;modifiers[:event][;text...]]u" — strip leading "[" and trailing "u"
        if (seq.Length < 3 || seq[0] != '[' || seq[^1] != 'u')
            return false;

        var inner = seq[1..^1];
        var semicolon = inner.IndexOf(';');

        int keycode;
        var modValue = 1; // default: no modifiers (1-based)

        if (semicolon < 0)
        {
            // No modifier field — just keycode (possibly with :alternate sub-fields we ignore).
            var keyPart = inner;
            var sub = keyPart.IndexOf(':');
            if (sub >= 0) keyPart = keyPart[..sub];
            if (!int.TryParse(keyPart, out keycode))
                return false;
        }
        else
        {
            var keyPart = inner[..semicolon];
            var subKey = keyPart.IndexOf(':');
            if (subKey >= 0) keyPart = keyPart[..subKey];
            if (!int.TryParse(keyPart, out keycode))
                return false;

            // Modifier field may have a :<event-type> sub-field, and a trailing ;<text-codepoints>.
            var rest = inner[(semicolon + 1)..];
            // Strip any trailing ;text-codepoints (we ignore associated text in the prototype).
            var nextSemi = rest.IndexOf(';');
            if (nextSemi >= 0) rest = rest[..nextSemi];

            var modPart = rest;
            var colon = rest.IndexOf(':');
            if (colon >= 0)
            {
                modPart = rest[..colon];
                if (!int.TryParse(rest[(colon + 1)..], out var eventType))
                    return false;
                if (eventType != 1) return true; // swallow repeat / release
            }
            if (!int.TryParse(modPart, out modValue) || modValue < 1) return false;
        }

        // Swallow modifier-key-alone press events (left/right Shift/Ctrl/Alt/Super/Hyper/Meta,
        // CapsLock, NumLock, etc.) — the kitty PUA range 57441..57454 carries these and they
        // overwhelm the prototype's input loop with noise on every keystroke.
        if (keycode is >= 57441 and <= 57454)
            return true; // parsed-and-swallowed

        // Decode 1-based modifier bitmask: value = 1 + (shift ? 1 : 0) + (alt ? 2 : 0) + (ctrl ? 4 : 0)
        var modBits = modValue - 1;
        var shift = (modBits & 1) != 0;
        var alt = (modBits & 2) != 0;
        var ctrl = (modBits & 4) != 0;

        var (consoleKey, keyChar) = MapKeycodeToConsoleKey(keycode);
        // Modifier-alone or unknown keys we don't want to surface get ConsoleKey.None and '\0' —
        // swallow them too rather than surfacing a confusing empty KeyPressed.
        if (consoleKey == ConsoleKey.None && keyChar == '\0')
            return true;

        result = new KeyPressed(new ConsoleKeyInfo(keyChar, consoleKey, shift, alt, ctrl));
        return true;
    }

    /// <summary>
    /// Maps a kitty keyboard protocol keycode (Unicode codepoint or functional key code)
    /// to a <see cref="ConsoleKey"/> and character.
    /// </summary>
    private static (ConsoleKey Key, char Char) MapKeycodeToConsoleKey(int keycode) => keycode switch
    {
        13 => (ConsoleKey.Enter, '\r'),
        9 => (ConsoleKey.Tab, '\t'),
        127 => (ConsoleKey.Backspace, '\b'),
        27 => (ConsoleKey.Escape, '\x1b'),
        // Printable ASCII range
        >= 32 and <= 126 => (CharToConsoleKey((char)keycode), (char)keycode),
        // Kitty functional-key PUA codepoints (https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional)
        57344 => (ConsoleKey.Escape, '\x1b'),
        57345 => (ConsoleKey.Enter, '\r'),
        57346 => (ConsoleKey.Tab, '\t'),
        57347 => (ConsoleKey.Backspace, '\b'),
        57348 => (ConsoleKey.Insert, '\0'),
        57349 => (ConsoleKey.Delete, '\0'),
        57350 => (ConsoleKey.LeftArrow, '\0'),
        57351 => (ConsoleKey.RightArrow, '\0'),
        57352 => (ConsoleKey.UpArrow, '\0'),
        57353 => (ConsoleKey.DownArrow, '\0'),
        57354 => (ConsoleKey.PageUp, '\0'),
        57355 => (ConsoleKey.PageDown, '\0'),
        57356 => (ConsoleKey.Home, '\0'),
        57357 => (ConsoleKey.End, '\0'),
        57358 => (ConsoleKey.None, '\0'), // CapsLock — no ConsoleKey constant; swallow.
        // F1..F12 (Kitty PUA 57364..57375)
        >= 57364 and <= 57375 => (ConsoleKey.F1 + (keycode - 57364), '\0'),
        // Default: use the codepoint as the char, no specific ConsoleKey
        _ => (ConsoleKey.None, keycode < 128 ? (char)keycode : '\0')
    };

    private static ConsoleKey CharToConsoleKey(char c) => c switch
    {
        >= 'a' and <= 'z' => ConsoleKey.A + (c - 'a'),
        >= 'A' and <= 'Z' => ConsoleKey.A + (c - 'A'),
        >= '0' and <= '9' => ConsoleKey.D0 + (c - '0'),
        ' ' => ConsoleKey.Spacebar,
        _ => ConsoleKey.None
    };

    /// <summary>
    /// Whether the terminal is currently reporting mouse coordinates in pixels (CSI ?1016h) rather
    /// than cells. When set, the raw coordinates are surfaced on <see cref="MouseEvent.PixelX"/> /
    /// <see cref="MouseEvent.PixelY"/>; consumers convert to cells using the terminal's font metrics.
    /// </summary>
    public bool PixelReporting { get; set; }

    /// <summary>
    /// Fully decodes an SGR mouse sequence and appends a rich <see cref="MouseEvent"/> to
    /// <paramref name="results"/>. Wheel events additionally append a legacy
    /// <see cref="MouseScrollEvent"/> so focused scrollables keep working unchanged.
    /// </summary>
    /// <param name="seq">The buffered sequence string, e.g. <c>[&lt;0;5;10M</c> (press) or <c>...m</c> (release).</param>
    /// <param name="results">List to append events into.</param>
    private void EmitMouseSgrEvent(string seq, List<IInputEvent> results)
    {
        // seq = "[<button;x;y" + terminator ('M' = press, 'm' = release).
        if (seq.Length < 3) return;
        var terminator = seq[^1];
        var isRelease = terminator == 'm';

        var inner = seq[2..^1]; // "button;x;y"
        var first = inner.IndexOf(';');
        if (first < 0) return;
        var second = inner.IndexOf(';', first + 1);
        if (second < 0) return;

        // Coordinates may legally be negative during drag-out and in pixel mode.
        if (!int.TryParse(inner[..first], out var button)) return;
        if (!int.TryParse(inner[(first + 1)..second], out var rawX)) return;
        if (!int.TryParse(inner[(second + 1)..], out var rawY)) return;

        var isWheel = (button & 0x40) != 0;
        var isExtended = (button & 0x80) != 0;
        var isMotion = (button & 0x20) != 0;
        var low2 = button & 0b11;

        var modifiers = (ConsoleModifiers)0;
        if ((button & 0x04) != 0) modifiers |= ConsoleModifiers.Shift;
        if ((button & 0x08) != 0) modifiers |= ConsoleModifiers.Alt;
        if ((button & 0x10) != 0) modifiers |= ConsoleModifiers.Control;

        // Wire coordinates are 1-based cells (or pixels under ?1016h). Convert to 0-based.
        int column, row, pixelX = -1, pixelY = -1;
        if (PixelReporting)
        {
            pixelX = rawX;
            pixelY = rawY;
            column = rawX; // caller divides by cell width using terminal font metrics
            row = rawY;
        }
        else
        {
            column = rawX - 1;
            row = rawY - 1;
        }

        MouseButton mouseButton;
        MouseEventKind kind;

        if (isWheel)
        {
            mouseButton = MouseButton.None;
            kind = low2 switch
            {
                0 => MouseEventKind.ScrollUp,
                1 => MouseEventKind.ScrollDown,
                2 => MouseEventKind.ScrollLeft,
                _ => MouseEventKind.ScrollRight,
            };
        }
        else if (isExtended)
        {
            mouseButton = low2 switch
            {
                0 => MouseButton.Back,
                1 => MouseButton.Forward,
                _ => MouseButton.None,
            };
            kind = isMotion
                ? (mouseButton == MouseButton.None ? MouseEventKind.Move : MouseEventKind.Drag)
                : (isRelease ? MouseEventKind.Up : MouseEventKind.Down);
        }
        else
        {
            // low2: 0=Left, 1=Middle, 2=Right, 3=no-button (motion with nothing held).
            mouseButton = low2 switch
            {
                0 => MouseButton.Left,
                1 => MouseButton.Middle,
                2 => MouseButton.Right,
                _ => MouseButton.None,
            };

            if (isMotion)
                kind = mouseButton == MouseButton.None ? MouseEventKind.Move : MouseEventKind.Drag;
            else
                kind = isRelease ? MouseEventKind.Up : MouseEventKind.Down;
        }

        results.Add(new MouseEvent(column, row, mouseButton, kind, modifiers, ClickChain: 1, pixelX, pixelY));

        // Preserve the legacy scroll path for focused IScrollable components.
        if (kind == MouseEventKind.ScrollUp)
            results.Add(new MouseScrollEvent(+1));
        else if (kind == MouseEventKind.ScrollDown)
            results.Add(new MouseScrollEvent(-1));
    }
}
